sets.exported={
    main="Kaja Sword",
    sub="Tauret",
    ammo="Homiliary",
    head={ name="Viti. Chapeau +3", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    body="Jhakri Robe +2",
    hands={ name="Viti. Gloves +1", augments={'Enhancing Magic duration',}},
    legs={ name="Carmine Cuisses", augments={'Accuracy+15','Attack+10','"Dual Wield"+5',}},
    feet={ name="Vitiation Boots +2", augments={'Immunobreak Chance',}},
    neck="Wiglen Gorget",
    waist="Flume Belt",
    left_ear="Thureous Earring",
    right_ear="Loquac. Earring",
    left_ring="Stikini Ring",
    right_ring="Stikini Ring",
    back={ name="Sucellos's Cape", augments={'STR+20','Accuracy+20 Attack+20','Attack+10','"Dual Wield"+10','Damage taken-5%',}},
}