sets.exported={
    main={ name="Grioavolr", augments={'"Fast Cast"+2','MND+9','Mag. Acc.+27','"Mag.Atk.Bns."+21','Magic Damage +2',}},
    sub="Mephitis Grip",
    ammo="Pemphredo Tathlum",
    head={ name="Viti. Chapeau +3", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    body={ name="Vanya Robe", augments={'MND+10','Spell interruption rate down +15%','"Conserve MP"+6',}},
    hands={ name="Helios Gloves", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','"Fast Cast"+5','INT+7 MND+7',}},
    legs={ name="Psycloth Lappas", augments={'MP+80','Mag. Acc.+15','"Fast Cast"+7',}},
    feet={ name="Medium's Sabots", augments={'MP+50','MND+8','"Conserve MP"+6','"Cure" potency +3%',}},
    neck={ name="Dls. Torque +1", augments={'Path: A',}},
    waist="Eschan Stone",
    left_ear="Gwati Earring",
    right_ear="Snotra Earring",
    left_ring="Stikini Ring",
    right_ring="Kishar Ring",
    back={ name="Sucellos's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','INT+10','"Mag.Atk.Bns."+10','Spell interruption rate down-10%',}},
}