sets.exported={
    main="Kaja Sword",
    sub="Kaja Knife",
    ammo="Impatiens",
    head={ name="Viti. Chapeau +2", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    body="Jhakri Robe +2",
    hands={ name="Helios Gloves", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','"Fast Cast"+5','INT+7 MND+7',}},
    legs={ name="Carmine Cuisses", augments={'Accuracy+15','Attack+10','"Dual Wield"+5',}},
    feet="Atrophy Boots +1",
    neck="Wiglen Gorget",
    waist="Fucho-no-Obi",
    left_ear="Thureous Earring",
    right_ear="Loquac. Earring",
    left_ring="Stikini Ring",
    right_ring="Stikini Ring",
    back={ name="Sucellos's Cape", augments={'STR+20','Accuracy+20 Attack+20','Attack+3','"Dual Wield"+10',}},
}