sets.exported={
    item="H. Kindred Crest",
    item="Abdhaljs Seal",
    item="Storage Slip 23",
    head={ name="Viti. Chapeau +2", augments={'Enfeebling Magic duration','Magic Accuracy',}},
    item="Copper Voucher",
    head="Atro. Chapeau +1",
    item="Storage Slip 16",
    hands="Jhakri Cuffs +2",
    item="Storage Slip 18",
    item="Kindred's Crest",
    item="Shihei",
    item="Storage Slip 21",
    item="Toolbag (Shihe)",
    hands="Spae. Gloves +1",
    item="S. Kindred Crest",
    body="Lethargy Sayon +1",
    body="Atrophy Tabard +1",
    hands="Atrophy Gloves +1",
    item="Darksteel Ingot",
    head={ name="Arch. Petasos +1", augments={'Increases Ancient Magic damage and magic burst damage',}},
    legs="Atrophy Tights +1",
    legs="Jhakri Slops +2",
    item="SP Gobbie Key",
    body="Jhakri Robe +2",
    hands={ name="Arch. Gloves +1", augments={'Increases Elemental Magic accuracy',}},
    left_ring="Capacity Ring",
    feet={ name="Arch. Sabots +1", augments={'Increases Aspir absorption amount',}},
    head="Wicce Petasos +1",
    body="Wicce Coat +1",
    item="Forbidden Key",
    item="Kindred's Seal",
    feet="Atrophy Boots +1",
    hands="Wicce Gloves +1",
    legs="Wicce Chausses +1",
    feet="Wicce Sabots +1",
    body={ name="Viti. Tabard +1", augments={'Enhances "Chainspell" effect',}},
    item="Chonofuda",
    feet={ name="Vitiation Boots +1", augments={'Immunobreak Chance',}},
    head="Leth. Chappel +1",
    sub="Nodal Wand",
    hands="Leth. Gantherots +1",
    left_ear="Sherida Earring",
    legs="Leth. Fuseau +1",
    feet="Leth. Houseaux +1",
    item="Dial Key #Ab",
    item="Gil",
    item="Kaiserin Cosme.",
    item="Prishe Statue",
    item="Odin Statue",
    item="Maple Table",
    neck="Sacro Gorget",
    range="Goldfish Basket",
    main="Kirin's Pole",
    sub="Egeking",
    item="Millionaire Desk",
    left_ring="Echad Ring",
    hands="Councilor's Cuffs",
    item="Flower Stand",
    main="Futsuno Mitama",
    sub={ name="Emissary", augments={'DMG:+15','Accuracy+15','Attack+15',}},
    item="T♂ Mannequin",
    item="H♂ Mannequin",
    ammo="Fullmetal Bullet",
    item="Forgotten Step",
    item="Forgotten Touch",
    item="Tableware Set",
    item="Forgotten Step",
    left_ring="Anniversary Ring",
    item="Prinseggstarta",
    item="Vana'clock",
    main="Cobra Staff",
    left_ring="Vocation Ring",
    item="Bonbori",
    ammo="Super Scoop",
    main="Fourth Staff",
    main="Ram Staff",
    main="Kaladanda",
    sub="Leviathan's Rod",
    item="Katana-kazari",
    item="Forgotten Hope",
    sub="Titan's Cudgel",
    item="Frgtn. Thought",
    item="Frgtn. Thought",
    sub={ name="Purgation", augments={'Attack+10','"Store TP"+6','Weapon skill damage +4%','DMG:+15',}},
    item="Flower Egg",
    main="Trick Staff II",
    neck="Rep. Stable Medal",
    ammo="Spirit Lantern",
    sub="Relic Maul",
    neck="Kgd. Stable Collar",
    sub="Garuda's Dagger",
    sub="Vorpal Sword",
    item="G. Bamboo Grass",
    item="Coral Crest Key",
    left_ear="Novia Earring",
    item="T.M.: Fortitude",
    item="Mannequin Legs",
    sub={ name="Rubicundity", augments={'Mag. Acc.+5','"Mag.Atk.Bns."+5','"Conserve MP"+4',}},
    left_ring="Homing Ring",
    item="Chocobo Bedding",
    item="B. Bamboo Grass",
    item="VCS Reg. Card",
    item="VCS Reg. Card",
    main={ name="Lehbrailg +2", augments={'DMG:+15','MND+7','"Mag.Atk.Bns."+30',}},
    item="Mannequin Hands",
    item="San d'Orian Flag",
    item="R. Bamboo Grass",
    back="Sacro Mantle",
    item="Mannequin Body",
    item="Lucky Egg",
    ammo="Gobbie Goodie Bag",
    item="Kadomatsu",
    item="Windurstian Flag",
    ammo="Moggie Goodie Bag",
    item="Mannequin Head",
    item="Bastokan Flag",
    neck="Fed. Stable Scarf",
    item="Frgtn. Journey",
    item="Imperial Standard",
    left_ring="Ice Ring",
    hands="Trainee Gloves",
    item="Red Pondweed",
    head="Glory Crown",
    head="Shaded Specs.",
    sub="Rose Couverte",
    feet="Rostrum Pumps",
    range="Animator",
    left_ring="Fire Ring",
    sub="Prudence Rod",
    neck="Fenrir's Torque",
    left_ring="Expertise Ring",
    main="Ramuh's Staff",
    neck="Colossus's Torque",
    left_ear="Diabolos's Earring",
    main="Hardwood Katana",
    item="Silver Mirror",
    left_ring="Diabolos's Ring",
    left_ring="Lightning Ring",
    sub="Raphael's Rod",
    left_ring="Water Ring",
    left_ring="Zodiac Ring",
    waist={ name="Tarutaru Sash", augments={'"Treasure Hunter"+1','HP+12',}},
    left_ring="Earth Ring",
    sub="Khandroma",
    main={ name="Twebuliij", augments={'MP+60','Mag. Acc.+15','MND+12',}},
    item="Copper Key",
    item="Magian Specs.",
    main="Diabolos's Pole",
    sub="Brunello",
    hands="Engineer's Gloves",
    item="Crystal Petrifact",
    left_ring="Dcl.Grd. Ring",
    sub="Mundus Shield",
    main="Paikea",
    left_ring="Duodec. Ring",
    item="Alfard's Fang",
    left_ring="Caliber Ring",
    item="Blue Pondweed",
    head="Hike Khat +1",
    feet={ name="Founder's Greaves", augments={'VIT+5','"Mag.Atk.Bns."+1','Mag. Evasion+2',}},
    main="Sowilo Claymore",
    sub="Glinting Shield",
    main="Hoe",
    item="White Drop",
    item="Purple Drop",
    head="Twilight Helm",
    body="Nocturnus Mail",
    left_ring="Tavnazian Ring",
    feet="Mannequin Pumps",
    main="Nativus Halberd",
    item="Centurio's Armor",
    left_ring="Minerva's Ring",
    left_ring="Empress Band",
    item="Centurio's Armor",
    main="Scepter Staff",
    main="Cronus",
    item="Celine's Vine",
    main="Carbuncle's Pole",
    item="Red Drop",
    item="Celine's Vine",
    left_ring="San d'Orian Ring",
    legs={ name="Artsieq Hose", augments={'MP+30','Mag. Acc.+20','MND+7',}},
    range="Lamiabane",
    left_ring="Bellona's Ring",
    body={ name="Artsieq Jubbah", augments={'MP+30','Mag. Acc.+20','MND+7',}},
    left_ring="Balrahn's Ring",
    waist="White Belt",
    body="Kirin's Osode",
    item="Centurio's Armor",
    legs={ name="Artsieq Hose", augments={'MP+30','"Mag.Atk.Bns."+20','INT+7',}},
    sub="Kasasagi",
    left_ring="Shadow Ring",
    body={ name="Helios Jacket", augments={'Mag. Acc.+18','"Fast Cast"+5','INT+4 MND+4',}},
    legs={ name="Hagondes Pants +1", augments={'Phys. dmg. taken -2%','"Mag.Atk.Bns."+13',}},
    main="Nightfall",
    left_ring="Olduum Ring",
    item="L. Jadeshell",
    item="Coalit. Fertilizer",
    item="Lightning Fewell",
    item="Herb Seeds",
    item="M. Silverpiece",
    item="Fourth Virtue",
    item="Tarutaru Rice",
    item="Seal of Suzaku",
    item="100 Byne Bill",
    item="Moat Carp",
    item="Ice Fewell",
    head="Straw Hat",
    item="Tarutaru Rice",
    item="O. Bronzepiece",
    item="T. Whiteshell",
    item="E. Tincture (IS)",
    item="Earth Fewell",
    item="San d'Or. Carrot",
    item="Tree Cuttings",
    item="Moat Carp",
    item="Water Fewell",
    item="Tree Cuttings",
    item="1 Byne Bill",
    item="Cactus Stems",
    item="Moat Carp",
    item="Moat Carp",
    item="Grove Cuttings",
    hands="Delegate's Cuffs",
    item="Fire Fewell",
    item="Herb Seeds",
    item="Fruit Seeds",
    item="Burdock",
    item="Fruit Seeds",
    item="Grow-M-Good",
    item="Grove Cuttings",
    item="Arborfruit Seed",
    item="Arborscent Seed",
    item="Wind Fewell",
    item="Moat Carp",
    item="Dark Fewell",
    item="Gem of the South",
    item="Chicken Bone",
    hands="Work Gloves",
    item="Summerstone",
    item="Vegetable Seeds",
    item="Luminicloth",
    item="Sunflower Seeds",
    item="Cotton Candy",
    item="Light Fewell",
    item="Grain Seeds",
    item="Willow Strongbox",
    item="Wood. Kit 5",
    sub="Debahocho",
    item="Moat Carp",
    item="Vegetable Seeds",
    item="Singed Buffalo",
    body="Delegate's Garb",
    item="Oily Blood",
    item="Behemoth Tongue",
    item="Wyrm Beard",
    item="Morbolger Vine",
    item="Gem of the West",
    item="Springstone",
    item="Akaso",
    item="Aquarian Tatter",
    item="Toolbag (Kagi)",
    item="Autumnstone",
    item="Diorite",
    item="Voiddust",
    item="Riftsand",
    item="Kupon I-Seal",
    item="Avidity Grimoire",
    item="Airlixir +2",
    item="Pluton",
    item="Silver Sea Card",
    item="Amrita",
    item="Airlixir",
    item="Beitetsu",
    item="Eschite Ore",
    item="Eschalixir",
    item="Eschalixir",
    item="Alexandrite",
    item="Gravewood Log",
    item="Eschalixir",
    item="Etched Memory",
    item="Gin's Scale",
    item="Airlixir +1",
    item="Eschalixir",
    item="Ethereal Incense",
    item="Eschalixir +2",
    item="Eschalixir +1",
    item="Silt Pouch",
    item="Ashweed",
    item="Eschalixir +1",
    item="Eschalixir +1",
    item="Bead Pouch",
    item="Riftborn Boulder",
    item="Distilled Water",
    item="Kin's Scale",
    item="Eschalixir",
    item="Hare Meat",
    item="Eschalixir +1",
    item="Eschalixir",
    item="Amrita",
    item="Ambrosia",
    item="Ambrosia",
    item="Ambrosia",
    item="Amrita",
    item="Ambrosia",
    item="Amrita",
    item="Ambrosia",
    item="Amrita",
    item="Amrita",
    item="Amrita",
    item="Ashweed",
    item="Genbu Scrap",
    sub="Flanged Grip",
    item="H-P Bayld",
    item="Grape Daifuku",
    item="Beitetsu",
    item="K. Snow Cone",
    item="Bhaflau Card",
    item="Arrapago Card",
    item="Ifritite",
    item="Ramuite",
    item="Leviatite",
    item="Melon Pie",
    item="Storage Slip 07",
    item="Light Geode",
    item="Aqua Geode",
    item="Storage Slip 12",
    item="Thunder Geode",
    item="Apple Pie",
    item="Snow Geode",
    item="Titanite",
    item="Storage Slip 20",
    item="Storage Slip 19",
    item="Carbite",
    item="Pear Crepe",
    item="Trbl. Pickaxe +1",
    item="Garudite",
    item="Shadow Geode",
    item="Storage Slip 15",
    item="El. Pachira Fruit",
    item="Amrita",
    item="Flame Geode",
    item="Storage Slip 04",
    item="Storage Slip 06",
    item="Rolanberry Pie",
    item="Linkpearl",
    item="Shivite",
    item="Soil Geode",
    item="Storage Slip 22",
    item="Storage Slip 11",
    item="Amrita",
    item="Storage Slip 02",
    item="Linkpearl",
    item="Toolbag (Shihe)",
    item="Fenrite",
    item="Trbl. Sickle +1",
    item="Kusamochi",
    item="Toolbag (Furu)",
    item="Linkpearl",
    neck="Chocobo Whistle",
    item="Echo Drops",
    item="Toolbag (Maki)",
    item="Sickle",
    item="Trbl. Hatchet",
    item="Linkpearl",
    item="Storage Slip 05",
    item="Echo Drops",
    item="Storage Slip 10",
    item="Silent Oil",
    item="Storage Slip 17",
    left_ear="Signal Pearl",
    item="Holy Water",
    item="Remedy",
    item="Storage Slip 08",
    item="Storage Slip 01",
    item="Storage Slip 03",
    item="Tavnazian Taco",
    item="Amrita",
    item="Toolbag (Hira)",
    item="Pearlsack",
    item="Rolan. Daifuku",
    item="Linkpearl",
    item="Miso Ramen",
    item="Remedy",
    item="Echo Drops",
    item="Smouldering Lamp",
    item="Pumpkin Pie",
    item="Shikanofuda",
    item="Amrita",
    item="Breeze Geode",
    item="Pickaxe",
    item="Trbl. Hatchet +1",
    item="Abdhaljs Needle",
    item="Cursed Dalmatica",
    item="Vrt. Stn. Pouch",
    item="Leujaoam Log",
    item="Pellucid Stone",
    item="Fern Stone",
    item="Lebros Chronicle",
    item="Abdhaljs Metal",
    item="Lustreless Scale",
    item="Periqia Diary",
    item="Faithful's Torso I",
    item="Abdhaljs Dust",
    legs="Psycloth Lappas",
    back="Disperser's Cape",
    ammo="Virtue Stone",
    back="Nexus Cape",
    item="Abdhaljs Thread",
    item="Fern Stone",
    item="Taupe Stone",
    item="Taupe Stone",
    head="Pursuer's Beret",
    legs="Pursuer's Pants",
    hands="Pursuer's Cuffs",
    item="Riftdross",
    neck="Subtlety Spec.",
    item="Abdhaljs Matter",
    item="Heavy Metal",
    body="Hexed Jacket -1",
    item="Lustreless Hide",
    item="Faithful's Legs I",
    item="Maze Tabula M01",
    item="Heavy Metal",
    left_ring="Mars's Ring",
    sub="Chocobo Wand",
    item="Abdhaljs Nugget",
    item="Pellucid Stone",
    item="Sunflower Seeds",
    item="Cirdas Visage I",
    head="Hexed Bonnet",
    left_ear="Dominance Earring",
    item="Abdhaljs Gem",
    item="Abdhaljs Nugget",
    item="Abdhaljs Anima",
    sub={ name="Schiavona", augments={'Attack+5',}},
    left_ear="Kocco's Earring",
    waist="Key Ring Belt",
    item="Ilrusi Ledger",
    item="MMM Member's Cd.",
    item="Mamool Ja Journal",
    main="Marin Staff +1",
    hands={ name="Otomi Gloves", augments={'HP+30','MP+30','Magic Damage +4',}},
    sub="Zuuxowu Grip",
    main={ name="Lathi", augments={'MP+80','INT+20','"Mag.Atk.Bns."+20',}},
    body={ name="Merlinic Jubbah", augments={'Mag. Acc.+23 "Mag.Atk.Bns."+23','CHR+3','Mag. Acc.+12','"Mag.Atk.Bns."+12',}},
    body="Annoint. Kalasiris",
    sub="Sors Shield",
    sub="Niobid Strap",
    hands="Treefeller Gloves",
    body={ name="Telchine Chas.", augments={'Enh. Mag. eff. dur. +7',}},
    hands="Dynasty Mitts",
    body="Trench Tunic",
    sub={ name="Tamaxchi", augments={'Mag. Acc.+30','Enmity-10',}},
    head={ name="Adhemar Bonnet", augments={'STR+10','DEX+10','Attack+15',}},
    body={ name="Amalric Doublet", augments={'MP+60','INT+10','Enmity-5',}},
    hands="Gende. Gages +1",
    body={ name="Gende. Bilaut +1", augments={'Phys. dmg. taken -3%','"Cure" potency +8%',}},
    hands={ name="Telchine Gloves", augments={'Mag. Acc.+15 "Mag.Atk.Bns."+15','"Cure" potency +6%','INT+7 MND+7',}},
    sub="Excalibur",
    body={ name="Taeon Tabard", augments={'Accuracy+16 Attack+16','"Dual Wield"+5','STR+4 VIT+4',}},
    ammo="Hasty Pinion +1",
    sub="Odium",
    sub="Bolelabunga",
    sub="Alber Strap",
    body={ name="Kaykaus Bliaut", augments={'MP+60','"Cure" potency +5%','"Conserve MP"+6',}},
    sub="Hocho",
    head="Midras's Helm +1",
    body={ name="Arch. Coat +3", augments={'Enhances "Manafont" effect',}},
    sub={ name="Queller Rod", augments={'Healing magic skill +15','"Cure" potency +10%','"Cure" spellcasting time -7%',}},
    ammo="Barathrum",
    head={ name="Hagondes Hat +1", augments={'Phys. dmg. taken -4%','Enmity-6',}},
    ammo="Sapience Orb",
    hands={ name="Adhemar Wristbands", augments={'STR+10','DEX+10','Attack+15',}},
    body={ name="Hagondes Coat +1", augments={'Phys. dmg. taken -4%','Magic dmg. taken -3%','Magic burst dmg.+10%',}},
    hands="Umuthi Gloves",
    body="Councilor's Garb",
    hands={ name="Chironic Gloves", augments={'"Cure" potency +8%','DEX+2','Magic Damage +14','Accuracy+4 Attack+4','Mag. Acc.+12 "Mag.Atk.Bns."+12',}},
    sub="Mephitis Grip",
    ammo="Pemphredo Tathlum",
    sub={ name="Solstice", augments={'MP+60','INT+15','"Mag.Atk.Bns."+15',}},
    hands={ name="Helios Gloves", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','"Fast Cast"+5','INT+7 MND+7',}},
    range="Antitail +1",
    head="Befouled Crown",
    body="Spaekona's Coat +2",
    head="Destrier Beret",
    main="Boonwell Staff",
    ammo="Ginsen",
    ammo="Homiliary",
    sub={ name="Emissary", augments={'Mag. Acc.+15','"Mag.Atk.Bns."+20','"Refresh"+1',}},
    head="Pixie Hairpin +1",
    head={ name="Merlinic Hood", augments={'Mag. Acc.+25 "Mag.Atk.Bns."+25','"Drain" and "Aspir" potency +2','STR+10','Mag. Acc.+11','"Mag.Atk.Bns."+12',}},
    ammo="Incantor Stone",
    head="Nahtirah Hat",
    range="Dunna",
    hands={ name="Fanatic Gloves", augments={'MP+40','Healing magic skill +4','"Conserve MP"+3','"Fast Cast"+4',}},
    hands={ name="Leyline Gloves", augments={'Accuracy+15','Mag. Acc.+15','"Mag.Atk.Bns."+15','"Fast Cast"+3',}},
    sub="Sacro Bulwark",
    hands={ name="Amalric Gages", augments={'INT+10','Mag. Acc.+15','"Mag.Atk.Bns."+15',}},
    hands={ name="Taeon Gloves", augments={'Accuracy+15 Attack+15','Weapon Skill Acc.+18',}},
    head={ name="Vanya Hood", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    head={ name="Kaykaus Mitra", augments={'MP+60','"Cure" spellcasting time -5%','Enmity-5',}},
    body="Shango Robe",
    sub="Achaq Grip",
    sub="Culminus",
    ammo="Impatiens",
    sub={ name="Beatific Shield +1", augments={'Phys. dmg. taken -4%','HP+21','Magic dmg. taken -2%',}},
    sub="Kaja Sword",
    sub="Kaja Knife",
    sub={ name="Genbu's Shield", augments={'"Cure" potency +2%','"Cure" spellcasting time -6%',}},
    body={ name="Vanya Robe", augments={'MND+10','Spell interruption rate down +15%','"Conserve MP"+6',}},
    body="Seidr Cotehardie",
    sub={ name="Colada", augments={'"Cure" potency +1%','INT+13','Mag. Acc.+18','"Mag.Atk.Bns."+16','DMG:+11',}},
    hands={ name="Hagondes Cuffs +1", augments={'Phys. dmg. taken -3%','"Avatar perpetuation cost" -4',}},
    head={ name="Carmine Mask", augments={'Accuracy+10','DEX+10','MND+15',}},
    hands={ name="Carmine Fin. Ga. +1", augments={'Rng.Atk.+20','"Mag.Atk.Bns."+12','"Store TP"+6',}},
    ammo="Seraphicaller",
    main={ name="Grioavolr", augments={'"Fast Cast"+2','MND+9','Mag. Acc.+27','"Mag.Atk.Bns."+21','Magic Damage +2',}},
    ammo="Dosis Tathlum",
    sub="Thuellaic Ecu +1",
    item="Wastebasket",
    item="Stationery Set",
    item="Tea Set",
    item="My First Magic Kit",
    item="Black VCS Plaque",
    item="Yel. VCS Plaque",
    item="Faded Crystal",
    item="Aurora Crystal",
    item="Heroism Aggregate",
    item="Gabbrath Horn",
    item="Beetle Blood",
    item="Damascene Cloth",
    item="Egg Buffet",
    item="Malboro Fiber",
    item="Waktza Rostrum",
    item="Beastmen's Medal",
    item="Galley Kitchen",
    item="Kupon A-PK109",
    item="Heroism Crystal",
    item="Refractive Crystal",
    item="Kindred's Medal",
    item="Heroism Crystal",
    item="Tr. Gr. Coffer.",
    item="Ym. Gr. Coffer",
    item="Gabbrath Meat",
    item="Li. Gr. Coffer",
    item="Du. Gr. Coffer",
    item="Refractive Crystal",
    item="Ig. Gr. Coffer",
    item="Gr. Gr. Coffer",
    item="Karakul Cloth",
    item="Sif's Lock",
    item="Thief's Tools",
    item="Refractive Crystal",
    item="Rockfin Tooth",
    item="Imp. Slv. Piece",
    item="Mog Pell (Green)",
    item="Raxa",
    item="Kupon A-EMI",
    item="Twill Damask",
    item="Oxblood",
    item="P. BLM Card",
    item="Black. I. Card",
    item="Rockfin Fin",
    item="Toolbag (Shika)",
    item="Kupon W-EMI",
    item="S. Astral Detritus",
    item="Jeunoan Flag",
    item="Cupboard",
    item="Celestial Globe",
    item="Mog Pell (Red)",
    item="Rusted I. Card",
    item="Raxa",
    item="Heroism Crystal",
    item="Siren's Hair",
    item="Imp. Gold Piece",
    item="Imp. Brz. Piece",
    item="Behem. Leather",
    item="Toolbag (Cho)",
    item="Toolbag (Ino)",
    item="Phoenix Feather",
    item="P. RDM Card",
    item="Voidleg: BLM",
    item="Harvest Pastry",
    item="P. BRD Card",
    item="Bztavian Stinger",
    item="Griffon Hide",
    item="P. MNK Card",
    body="Koga Chainmail",
    item="P. DRK Card",
    item="Imp. Silk Cloth",
    item="Damascus Ingot",
    item="Bztavian Wing",
    head="Koga Hatsuburi",
    back="Vates Cape +1",
    back="Izdubar Mantle",
    back={ name="Sucellos's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','"Fast Cast"+10','Damage taken-2%',}},
    back={ name="Lifestream Cape", augments={'Geomancy Skill +10','Indi. eff. dur. +19','Pet: Damage taken -5%',}},
    back={ name="Taranus's Cape", augments={'INT+20','Mag. Acc+20 /Mag. Dmg.+20','Mag. Acc.+2','"Mag.Atk.Bns."+10','Spell interruption rate down-10%',}},
    back={ name="Mecisto. Mantle", augments={'Cap. Point+47%','DEF+2',}},
    feet="Hag. Sabots +1",
    back={ name="Toutatis's Cape", augments={'DEX+20','Accuracy+20 Attack+20','Accuracy+7','"Store TP"+10','Phys. dmg. taken-10%',}},
    back="Perimede Cape",
    neck="Orunmila's Torque",
    back={ name="Alaunus's Cape", augments={'MND+20','Mag. Acc+20 /Mag. Dmg.+20','MND+10','"Fast Cast"+10','Phys. dmg. taken-10%',}},
    waist="Patentia Sash",
    neck="Incanter's Torque",
    feet="Herald's Gaiters",
    back="Umbra Cape",
    legs={ name="Chironic Hose", augments={'DEX+3','Attack+10','"Treasure Hunter"+1','Accuracy+7 Attack+7','Mag. Acc.+5 "Mag.Atk.Bns."+5',}},
    legs="Querkening Brais",
    back="Oretania's Cape",
    legs={ name="Arch. Tonban +2", augments={'Increases Elemental Magic debuff time and potency',}},
    back={ name="Mending Cape", augments={'Healing magic skill +9','Enha.mag. skill +7','Mag. Acc.+7',}},
    neck="Malison Medallion",
    feet="Gende. Galosh. +1",
    feet="Battlecast Gaiters",
    feet="Inspirited Boots",
    legs={ name="Taeon Tights", augments={'Attack+25','"Triple Atk."+2','Crit. hit damage +2%',}},
    legs={ name="Psycloth Lappas", augments={'MP+80','Mag. Acc.+15','"Fast Cast"+7',}},
    waist="Yamabuki-no-Obi",
    neck="Erra Pendant",
    feet="Regal Pumps +1",
    legs={ name="Amalric Slops", augments={'MP+60','"Mag.Atk.Bns."+20','Enmity-5',}},
    back="Atheling Mantle",
    waist="Refoccilation Stone",
    feet={ name="Taeon Boots", augments={'Accuracy+14','"Dual Wield"+3','VIT+5',}},
    back="Refraction Cape",
    waist="Prosilio Belt +1",
    waist="Eschan Stone",
    feet={ name="Medium's Sabots", augments={'MP+50','MND+8','"Conserve MP"+6','"Cure" potency +3%',}},
    feet="Agrarian Boots",
    neck="Mizu. Kubikazari",
    feet="Umbani Boots",
    back={ name="Canny Cape", augments={'DEX+4','AGI+4','"Dual Wield"+1',}},
    legs={ name="Kaykaus Tights", augments={'MP+60','Spell interruption rate down +10%','"Cure" spellcasting time -5%',}},
    waist="Sekhmet Corset",
    back="Toro Cape",
    waist="Cetl Belt",
    legs="Assid. Pants +1",
    waist="Fucho-no-Obi",
    waist="Windbuffet Belt +1",
    neck="Erudit. Necklace",
    feet={ name="Helios Boots", augments={'Mag. Acc.+20 "Mag.Atk.Bns."+20','"Drain" and "Aspir" potency +7','Magic burst dmg.+8%',}},
    feet="Tutyr Sabots",
    neck="Wiglen Gorget",
    legs="Fisherman's Hose",
    neck="Sanctity Necklace",
    neck="Asperity Necklace",
    legs="Field Hose",
    legs="Dredger Hose",
    legs={ name="Carmine Cuisses", augments={'Accuracy+15','Attack+10','"Dual Wield"+5',}},
    waist="Sinew Belt",
    feet={ name="Carmine Greaves +1", augments={'Accuracy+12','DEX+12','MND+20',}},
    back="Nantosuelta's Cape",
    back={ name="Sucellos's Cape", augments={'STR+20','Accuracy+20 Attack+20','Attack+3','"Dual Wield"+10',}},
    neck="Loricate Torque +1",
    feet={ name="Vanya Clogs", augments={'Healing magic skill +20','"Cure" spellcasting time -7%','Magic dmg. taken -3',}},
    neck="Combatant's Torque",
    back="Pahtli Cape",
    back={ name="Ghostfyre Cape", augments={'Enfb.mag. skill +8','Enha.mag. skill +1','Enh. Mag. eff. dur. +17',}},
    back={ name="Bane Cape", augments={'Elem. magic skill +4','Dark magic skill +10','"Mag.Atk.Bns."+4',}},
    back="Seshaw Cape",
    back="Swith Cape",
    waist="Hachirin-no-Obi",
    waist="Hierarch Belt",
    waist="Ninurta's Sash",
    waist="Flume Belt",
    waist="Witful Belt",
    left_ear="Barkaro. Earring",
    left_ear="Reraise Earring",
    neck={ name="Jeweled Collar", augments={'MND+3','MP recovered while healing +3','INT+3',}},
    left_ring="Facility Ring",
    left_ring="Meridian Ring",
    left_ear="Odnowa Earring +1",
    left_ring="Rufescent Ring",
    left_ear="Telos Earring",
    neck="Arciela's Grace +1",
    neck="Lissome Necklace",
    neck="Saevus Pendant +1",
    neck="Stoicheion Medal",
    left_ear="Earthcry Earring",
    head="Accord Hat +1",
    body="Iuitl Vest +1",
    body={ name="Qaaxo Harness", augments={'----------------',}},
    body="Mekosu. Harness",
    left_ear="Steelflash Earring",
    left_ear="Bladeborn Earring",
    left_ear="Dudgeon Earring",
    left_ear="Heartseeker Earring",
    left_ring="Stikini Ring",
    left_ring="Stikini Ring",
    left_ring="Emporox's Ring",
    body={ name="Samnuha Coat", augments={'Mag. Acc.+7','"Fast Cast"+2',}},
    body="Emet Harness +1",
    left_ring="Endorsement Ring",
    left_ring="Adoulin Ring +1",
    left_ring="Warp Ring",
    left_ring="Defending Ring",
    left_ring="Rajas Ring",
    left_ring="Sirona's Ring",
    left_ring="Mujin Band",
    left_ring="Archon Ring",
    left_ring="Prolix Ring",
    left_ear="Mendi. Earring",
    left_ring="Locus Ring",
    left_ring="Sangoma Ring",
    left_ring="Globidonta Ring",
    left_ring="Fenrir Ring +1",
    left_ring="Shiva Ring +1",
    left_ring="Shiva Ring +1",
    left_ring="Levia. Ring +1",
    left_ring="Mephitas's Ring +1",
    left_ring="Mephitas's Ring",
    left_ring="Trizek Ring",
    left_ring="Dim. Ring (Holla)",
    left_ear="Zennaroi Earring",
    left_ear="Odr Earring",
    left_ear="Glorious Earring",
    left_ear="Nourish. Earring +1",
    left_ear="Enchntr. Earring +1",
    left_ear="Gwati Earring",
    left_ear="Friomisi Earring",
    left_ear={ name="Moonshade Earring", augments={'Attack+4','TP Bonus +250',}},
    left_ear="Loquac. Earring",
    left_ear="Brutal Earring",
    left_ear="Suppanomimi",
    left_ear="Static Earring",
    left_ear="Relaxing Earring",
    head={ name="Apogee Crown", augments={'Pet: Attack+20','Pet: "Mag.Atk.Bns."+20','Blood Pact Dmg.+7',}},
    body="Passion Jacket",
    head="Whirlpool Mask",
    head="Felistris Mask",
    left_ring="Menelaus's Ring",
    left_ring="Excelsis Ring",
    left_ear="Handler's Earring",
    left_ear="Thureous Earring",
    neck="Gaudryi Necklace",
    head="Lithelimb Cap",
    left_ear="Snotra Earring",
    body={ name="Rawhide Vest", augments={'HP+50','"Subtle Blow"+7','"Triple Atk."+2',}},
    head="Imp. Wing Hairpin",
    left_ring="Haoma's Ring",
    head="Gavialis Helm",
    left_ring="Lebeche Ring",
    head={ name="Lilitu Headpiece", augments={'STR+6','DEX+7','Attack+12',}},
    left_ear="Ishvara Earring",
    left_ear="Dedition Earring",
    back={ name="Niht Mantle", augments={'Attack+9','Dark magic skill +6',}},
    back={ name="Weard Mantle", augments={'VIT+5',}},
    back={ name="Anchoret's Mantle", augments={'STR+3','DEX+5','"Subtle Blow"+3','"Counter"+1',}},
    back={ name="Mauler's Mantle", augments={'DEX+3','STR+3','Accuracy+2',}},
    back="Meanagh Cape +1",
    back="Agema Cape",
    waist="Shadow Belt",
    waist="Chaac Belt",
    waist="Klouskap Sash",
    legs="Augury Cuisses",
    feet={ name="Merlinic Crackows", augments={'Mag. Acc.+23 "Mag.Atk.Bns."+23','Phys. dmg. taken -1%','AGI+6','Mag. Acc.+10','"Mag.Atk.Bns."+12',}},
    feet={ name="Qaaxo Leggings", augments={'Accuracy+15','STR+7','Phys. dmg. taken -3',}},
    legs={ name="Qaaxo Tights", augments={'Accuracy+15','STR+7','Phys. dmg. taken -3',}},
    hands="Pursuer's Cuffs",
    range="Aureole",
    sub="Umbra Strap",
    sub="Tzacab Grip",
    sub="Vox Grip",
    legs="Avatara Slops",
    sub={ name="Shijo", augments={'DEX+15','"Dual Wield"+5','"Triple Atk."+2',}},
    sub="Ternion Dagger +1",
    sub={ name="Aizushintogo", augments={'DMG:+15','STR+15','Attack+15',}},
    main="Ababinili +1",
    main={ name="Keraunos", augments={'Pet: "Mag.Atk.Bns."+15','Pet: Haste+5','CHR+6',}},
    main="Gridarvor",
    range="Tsoa. Crossbow",
    left_ear="Eabani Earring",
    ammo="Honed Tathlum",
    ammo="Inlamvuyeso",
    sub={ name="Ochu", augments={'STR+5','DEX+3','Ninjutsu skill +2',}},
    sub={ name="Claidheamh Soluis", augments={'Mag. Evasion+8','Magic burst dmg.+1%',}},
    sub="Arendsi Fleuret",
    sub="Pukulatmuj +1",
    hands="Hegira Wristbands",
    sub="Izhiikoh",
    sub="Sandung",
    sub="Jugo Kukri +1",
    sub={ name="Taming Sari", augments={'STR+7','DEX+8','DMG:+6',}},
    left_ring="Oneiros Ring",
    left_ring="Hetairoi Ring",
    left_ear="Terminus Earring",
    left_ear="Gelai Earring",
    back="Vespid Mantle",
    back={ name="Evasionist's Cape", augments={'Enmity+4','"Dbl.Atk."+1','Damage taken-2%',}},
    back={ name="Toetapper Mantle", augments={'"Store TP"+3','"Rev. Flourish"+28',}},
    back={ name="Dispersal Mantle", augments={'STR+2','DEX+4','Pet: TP Bonus+380',}},
    back={ name="Gunslinger's Cape", augments={'Enmity-5','"Mag.Atk.Bns."+2','"Phantom Roll" ability delay -1','Weapon skill damage +1%',}},
    back={ name="Cornflower Cape", augments={'MP+26','DEX+1','Accuracy+4','Blue Magic skill +6',}},
    back={ name="Updraft Mantle", augments={'STR+5','Pet: Breath+3','Pet: Damage taken -1%',}},
    back={ name="Yokaze Mantle", augments={'STR+4','Sklchn.dmg.+2%','Weapon skill damage +1%',}},
    back={ name="Takaha Mantle", augments={'STR+3','"Zanshin"+1','"Store TP"+3','Meditate eff. dur. +4',}},
    back={ name="Lutian Cape", augments={'STR+5','AGI+3','"Store TP"+1','"Snapshot"+1',}},
    back={ name="Rhapsode's Cape", augments={'HP+18','Mag. Acc.+2','Enmity-10','Damage taken-2%',}},
    back={ name="Pastoralist's Mantle", augments={'STR+3 DEX+3','Accuracy+2','Pet: Accuracy+12 Pet: Rng. Acc.+12',}},
    left_ring="Evoker's Ring",
    left_ring="Fervor Ring",
    left_ring="Ayanmo Ring",
    left_ear="Novio Earring",
    left_ear="Gifted Earring",
    left_ear="Sanare Earring",
    left_ear="Andoaa Earring",
    left_ear="Domes. Earring",
    left_ear="Evans Earring",
    left_ear="Gelos Earring",
    back={ name="Conveyance Cape", augments={'Summoning magic skill +2','Pet: Enmity+5','Blood Pact Dmg.+1','Blood Pact ab. del. II -2',}},
    back="Samanisi Cape",
    back="Kumbira Cape",
    back="Argocham. Mantle",
    back="Moonbeam Cape",
    waist="Field Rope",
    waist="Mujin Obi",
    waist="Jaq'ij Sash",
    waist="Kuku Stone",
    waist="Famine Sash",
    feet={ name="Merlinic Crackows", augments={'"Mag.Atk.Bns."+30','Magic burst dmg.+10%','Mag. Acc.+3',}},
    hands="Regimen Mittens",
    range="Lu Shang's F. Rod",
    body={ name="Herculean Vest", augments={'Rng.Atk.+25','Weapon skill damage +3%','DEX+9','Accuracy+2','Attack+1',}},
    legs={ name="Enticer's Pants", augments={'MP+50','Pet: Accuracy+13 Pet: Rng. Acc.+13','Pet: Mag. Acc.+14','Pet: Damage taken -4%',}},
    legs={ name="Helios Spats", augments={'Pet: Accuracy+10 Pet: Rng. Acc.+10','"Avatar perpetuation cost" -4','Pet: Haste+5',}},
}