sets.exported={
    main={ name="Solstice", augments={'MP+60','INT+15','"Mag.Atk.Bns."+15',}},
    sub="Culminus",
    range="Dunna",
    head="Befouled Crown",
    body="Azimuth Coat +1",
    hands={ name="Bagua Mitaines +1", augments={'Enhances "Curative Recantation" effect',}},
    legs="Assid. Pants +1",
    feet={ name="Merlinic Crackows", augments={'Mag. Acc.+23 "Mag.Atk.Bns."+23','Phys. dmg. taken -1%','AGI+6','Mag. Acc.+10','"Mag.Atk.Bns."+12',}},
    neck="Sanctity Necklace",
    waist="Fucho-no-Obi",
    left_ear={ name="Moonshade Earring", augments={'Mag. Acc.+4','Latent effect: "Refresh"+1',}},
    right_ear="Loquac. Earring",
    left_ring="Defending Ring",
    right_ring="Rajas Ring",
    back="Umbra Cape",
}